#!/usr/bin/env bash
# shellcheck source=./lib/common.sh
# Описание: единственный авторитетный источник правил nftables для llm-lab.
#   Таблицы:
#     ip   llm_lab_nat    — DNAT (WAN→nginx) + masquerade (internal→WAN)
#     inet llm_lab_filter — forward whitelist
#
#   Вызывай ПОСЛЕ proxy-deploy-nginx-proxy.sh (нужен NGINX_IP).
#   Идемпотентно: flush → apply → persist при каждом запуске.
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
load_config
require_root
require_cmd nft

# NGINX_IP не экспортируется из load_config явно — берём из NGINX_WAN_IP
NGINX_IP="${NGINX_IP:-${NGINX_WAN_IP%/*}}"
NGINX_IP="${NGINX_IP:-10.10.10.70}"

[[ -n "$LLM_IP" ]]          || die "LLM_IP is not set"
[[ -n "$MONITORING_IP" ]]   || die "MONITORING_IP is not set"
[[ -n "$NGINX_IP" ]]        || die "NGINX_IP is not set"
[[ -n "$INTERNAL_SUBNET" ]] || die "INTERNAL_SUBNET is not set"
[[ -n "$INTERNAL_GATEWAY" ]] || die "INTERNAL_GATEWAY is not set"
[[ -n "$WAN_BRIDGE" ]]      || die "WAN_BRIDGE is not set"

mark_step "Configuring nftables for llm-lab"
info "  LLM_IP=$LLM_IP  MONITORING_IP=$MONITORING_IP  NGINX_IP=$NGINX_IP"
info "  SUBNET=$INTERNAL_SUBNET  WAN=$WAN_BRIDGE"

# ---------------------------------------------------------------------------
backup_ruleset() {
  local backup="/etc/nftables-backup-$(date +%Y%m%d%H%M%S).conf"
  nft list ruleset > "$backup" 2>/dev/null || true
  info "Ruleset backed up to ${backup}"
}

# ---------------------------------------------------------------------------
# Флашим ВСЕ таблицы, которые когда-либо создавал проект (включая старые имена)
flush_lab_tables() {
  info "Flushing old lab tables"
  local tables=(
    "ip   llm_lab_nat"
    "inet llm_lab_filter"
    "inet llm_lab"          # старое имя из common.sh::nftables_whitelist_config
    "inet pve_lab"          # было в ранних версиях
    "ip   nat"              # иногда создавали вручную
  )
  for t in "${tables[@]}"; do
    # shellcheck disable=SC2086
    nft delete table $t 2>/dev/null && info "Deleted table: $t" || true
  done
}

# ---------------------------------------------------------------------------
apply_ruleset() {
  info "Applying nftables ruleset"

  # Heredoc без кавычек — shell раскрывает переменные здесь, на хосте.
  # Переменные nft-синтаксиса (не shell) экранировать не нужно.
  nft -f - <<EOF
# llm-lab nftables ruleset — generated by infra-setup-nft-rules.sh
# DO NOT EDIT /etc/nftables-llm-lab.conf вручную — он перезаписывается скриптом.

table ip llm_lab_nat {

  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
    # DNAT: входящий WAN-трафик → nginx proxy
    iifname "${WAN_BRIDGE}" tcp dport { 3000, 8080, 9090, 9093, 11434 } \
      dnat ip to "${NGINX_IP}"
  }

  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;
    # masquerade: внутренняя подсеть → WAN
    ip saddr ${INTERNAL_SUBNET} oifname "${WAN_BRIDGE}" masquerade
  }
}

table inet llm_lab_filter {

  chain forward {
    type filter hook forward priority filter; policy drop;

    # 1. Разрешаем уже установленные / связанные соединения
    ct state established,related accept

    # 2. Внутренняя подсеть → WAN (после masquerade)
    ip saddr ${INTERNAL_SUBNET} oifname "${WAN_BRIDGE}" accept

    # 3. Входящие DNAT-пакеты к nginx proxy
    ip daddr ${NGINX_IP} tcp dport { 3000, 8080, 9090, 9093, 11434 } accept

    # 4. nginx proxy → LLM VM
    ip saddr ${NGINX_IP} ip daddr ${LLM_IP} \
      tcp dport { 3000, 11434 } accept

    # 5. nginx proxy → Monitoring VM
    ip saddr ${NGINX_IP} ip daddr ${MONITORING_IP} \
      tcp dport { 3000, 9090, 9093, 9100 } accept

    # 6. Prometheus (monitoring) → node/gpu-exporters на LLM VM
    ip saddr ${MONITORING_IP} ip daddr ${MONITORING_IP} accept
    ip saddr ${MONITORING_IP} ip daddr ${LLM_IP} \
      tcp dport { 9100, 9400 } accept

    # 7. Запрет VM→VM, кроме явно разрешённого выше.
    #    Шлюз (хост) не режем — он не в INTERNAL_SUBNET как daddr при форварде.
    ip saddr ${INTERNAL_SUBNET} ip daddr ${INTERNAL_SUBNET} drop
  }

  chain input  { type filter hook input  priority filter; policy accept; }
  chain output { type filter hook output priority filter; policy accept; }
}
EOF
  info "nftables ruleset applied"
}

# ---------------------------------------------------------------------------
# Persist: пишем отдельный файл с литеральными IP (из 'nft list'),
# чтобы systemd мог восстановить правила после reboot без переменных оболочки.
persist_ruleset() {
  info "Persisting ruleset to /etc/nftables-llm-lab.conf"

  # Перезаписываем (не append) — идемпотентно
  nft list table ip   llm_lab_nat    >  /etc/nftables-llm-lab.conf
  nft list table inet llm_lab_filter >> /etc/nftables-llm-lab.conf

  # Один include в /etc/nftables.conf — добавляем только если ещё нет
  if ! grep -qF 'nftables-llm-lab.conf' /etc/nftables.conf 2>/dev/null; then
    echo 'include "/etc/nftables-llm-lab.conf"' >> /etc/nftables.conf
    info "Added include to /etc/nftables.conf"
  fi

  systemctl enable nftables 2>/dev/null || true
  info "Rules will survive reboot via /etc/nftables-llm-lab.conf"
}

# ---------------------------------------------------------------------------
verify_ruleset() {
  info "Verifying ruleset"
  nft list table ip   llm_lab_nat
  nft list table inet llm_lab_filter
}

print_summary() {
  local pub="${PROXMOX_HOST:-<proxmox-ip>}"
  info "DNAT active on ${pub}:"
  info "  :3000  → ${NGINX_IP}:3000  (Grafana)"
  info "  :8080  → ${NGINX_IP}:8080  (Open WebUI)"
  info "  :9090  → ${NGINX_IP}:9090  (Prometheus)"
  info "  :9093  → ${NGINX_IP}:9093  (Alertmanager)"
  info "  :11434 → ${NGINX_IP}:11434 (Ollama API)"
}

# ---------------------------------------------------------------------------
backup_ruleset
flush_lab_tables
apply_ruleset
persist_ruleset
verify_ruleset
print_summary

audit_log "nftables llm-lab rules applied (LLM=${LLM_IP} MON=${MONITORING_IP} NGX=${NGINX_IP})"
