#!/usr/bin/env bash
# shellcheck source=./lib/common.sh
# Описание: Создаёт LXC контейнер с nginx reverse proxy на внутреннем бридже.
# DNAT и firewall настраиваются скриптом infra-setup-nft-rules.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
load_config
require_root
require_cmd pct

# TLS configuration
SSL_CERT="${SSL_CERT:-/etc/ssl/certs/nginx-selfsigned.crt}"
SSL_KEY="${SSL_KEY:-/etc/ssl/private/nginx-selfsigned.key}"

NGINX_CTID="${NGINX_CTID:-130}"
NGINX_HOSTNAME="${NGINX_HOSTNAME:-nginx-proxy}"
NGINX_STORAGE="${NGINX_STORAGE:-local-lvm}"
NGINX_DISK_GB="${NGINX_DISK_GB:-8}"
NGINX_MEMORY_MB="${NGINX_MEMORY_MB:-512}"
NGINX_CORES="${NGINX_CORES:-1}"
NGINX_IP="${NGINX_WAN_IP:-10.10.10.70/24}"
NGINX_GW="${NGINX_WAN_GW:-10.10.10.1}"
NGINX_IP_ONLY="${NGINX_IP%%/*}"
LLM_IP="${LLM_IP:-10.10.10.50}"
MONITORING_IP="${MONITORING_IP:-10.10.10.60}"
PROXMOX_PUB_IP="${PROXMOX_HOST:-}"
PROXMOX_USER="${PROXMOX_USER:-root@pam}"

[[ -n "$PROXMOX_PUB_IP" ]] || die "PROXMOX_HOST not set in infra.yaml"

mark_step "Deploying nginx proxy LXC ${NGINX_CTID}"

# ---------------------------------------------------------------------------
# Install SSL dependencies (must be before configure_nginx)
# ---------------------------------------------------------------------------
install_ssl_dependencies() {
  info "Installing SSL dependencies (openssl) in LXC ${NGINX_CTID}"
  pct exec "$NGINX_CTID" -- bash -c "
    set -Eeuo pipefail
    apt-get update -qq
    apt-get install -y -qq openssl
    echo 'openssl installed'
  " || warn "openssl installation skipped"
}

# ---------------------------------------------------------------------------
# Generate self-signed certificate (must be before configure_nginx)
# ---------------------------------------------------------------------------
generate_selfsigned_cert() {
  info "Generating self-signed SSL certificate"
  
  pct exec "$NGINX_CTID" -- bash -c "
    set -Eeuo pipefail
    mkdir -p /etc/ssl/private
    chmod 700 /etc/ssl/private
    
    # Generate self-signed cert if not exists
    if [ ! -f ${SSL_KEY} ] || [ ! -f ${SSL_CERT} ]; then
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout ${SSL_KEY} \
        -out ${SSL_CERT} \
        -subj \"/C=RU/ST=Moscow/L=Moscow/O=LLMLab/OU=IT/CN=77.50.132.85\" 2>/dev/null
      chmod 600 ${SSL_KEY}
      echo 'Self-signed certificate generated'
    else
      echo 'SSL certificate already exists'
    fi
  "
}

download_lxc_template() {
  local tmpl_name
  tmpl_name="$(basename "$LXC_TEMPLATE" | sed 's/^local:vztmpl\///')"
  local tmpl_path="/var/lib/vz/template/cache/${tmpl_name}"

  if [[ -f "$tmpl_path" ]]; then
    info "LXC template already exists: ${tmpl_path}"
    return 0
  fi

  info "Downloading LXC template..."
  pveam update
  pveam download local "${tmpl_name}" \
    || die "Failed to download template ${tmpl_name}. Run: pveam available --section system"
}

create_container() {
  if pct status "$NGINX_CTID" >/dev/null 2>&1; then
    info "Container ${NGINX_CTID} already exists, skipping creation"
    return 0
  fi

  info "Creating LXC container ${NGINX_CTID} on ${INTERNAL_BRIDGE} with IP ${NGINX_IP}"

  pct create "$NGINX_CTID" "$LXC_TEMPLATE" \
    --hostname "$NGINX_HOSTNAME" \
    --storage "$NGINX_STORAGE" \
    --rootfs "${NGINX_STORAGE}:${NGINX_DISK_GB}" \
    --memory "$NGINX_MEMORY_MB" \
    --cores "$NGINX_CORES" \
    --ostype ubuntu \
    --unprivileged 1 \
    --features nesting=1 \
    --net0 "name=eth0,bridge=${INTERNAL_BRIDGE},ip=${NGINX_IP},gw=${NGINX_GW}" \
    --nameserver "${DNS_SERVER:-1.1.1.1}" \
    --ssh-public-keys "$SSH_PUBLIC_KEY" \
    --start 1 \
    --onboot 1

  info "Container ${NGINX_CTID} created"
}

wait_for_container() {
  info "Waiting for container to be ready"
  local waited=0
  while ! pct exec "$NGINX_CTID" -- true 2>/dev/null; do
    sleep 3; waited=$((waited + 3))
    if (( waited > 60 )); then
      die "Container ${NGINX_CTID} not responding after 60s"
    fi
  done
  info "Container is ready"
}

install_nginx() {
  info "Installing nginx in container ${NGINX_CTID}"
  pct exec "$NGINX_CTID" -- bash -c "
    set -Eeuo pipefail
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y nginx curl
    systemctl enable nginx
    echo 'nginx installed'
  "
}

configure_nginx() {
  info "Configuring nginx reverse proxy with TLS"

  local nginx_conf
  nginx_conf="$(cat <<EOF
# llm-lab nginx reverse proxy with TLS
# Generated by proxy-deploy-nginx-proxy.sh

# HTTP to HTTPS redirect
server {
    listen 80;
    server_name _;
    return 301 https://\$host\$request_uri;
}

# HTTPS server - unified entry point
server {
    listen 443 ssl http2;
    server_name _;

    ssl_certificate     ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Open WebUI (root path)
    location / {
        proxy_pass         http://${LLM_IP}:3000;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    # Ollama API
    location /ollama/ {
        proxy_pass         http://${LLM_IP}:11434/;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        client_max_body_size 0;
    }

    # Prometheus
    location /prometheus/ {
        proxy_pass         http://${MONITORING_IP}:9090/;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }

    # Grafana
    location /grafana/ {
        proxy_pass         http://${MONITORING_IP}:3000/;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
    }

    # Alertmanager
    location /alertmanager/ {
        proxy_pass         http://${MONITORING_IP}:9093/;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }
}
EOF
)"

  pct exec "$NGINX_CTID" -- bash -c "
    cat > /etc/nginx/sites-available/llm-lab << 'NGINXEOF'
${nginx_conf}
NGINXEOF
    ln -sf /etc/nginx/sites-available/llm-lab /etc/nginx/sites-enabled/llm-lab
    rm -f /etc/nginx/sites-enabled/default
    nginx -t
    systemctl reload nginx
    echo 'nginx configured'
  "
}

verify_nginx() {
  info "Verifying nginx in container"
  pct exec "$NGINX_CTID" -- bash -c "
    systemctl is-active nginx
    echo 'Listening ports:'
    ss -tlnp | grep nginx || true
  " 2>/dev/null || true
}

print_access_info() {
  info "Nginx proxy deployed — LXC ${NGINX_CTID}, internal IP: ${NGINX_IP_ONLY}"
  info "Run infra-setup-nft-rules.sh to configure DNAT and firewall"
  info "After that access via HTTPS://77.50.132.85:"
  info "  Open WebUI:    https://77.50.132.85/"
  info "  Ollama API:    https://77.50.132.85/ollama/"
  info "  Prometheus:    https://77.50.132.85/prometheus/"
  info "  Grafana:       https://77.50.132.85/grafana/"
  info "  Alertmanager:  https://77.50.132.85/alertmanager/"
}

download_lxc_template
create_container
wait_for_container
fix_locale "$NGINX_CTID"
install_nginx
install_ssl_dependencies
generate_selfsigned_cert
configure_nginx
verify_nginx
print_access_info

audit_log "Nginx proxy LXC ${NGINX_CTID} deployed"
