#!/usr/bin/env bash
# shellcheck source=./lib/common.sh
# Описание: Создаёт LXC контейнер с nginx reverse proxy на внутреннем бридже.
# DNAT и firewall настраиваются скриптом infra-setup-nft-rules.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
load_config
require_root
require_cmd pct

NGINX_CTID="${NGINX_CTID:-130}"
NGINX_HOSTNAME="${NGINX_HOSTNAME:-nginx-proxy}"
NGINX_STORAGE="${NGINX_STORAGE:-local-lvm}"
NGINX_DISK_GB="${NGINX_DISK_GB:-8}"
NGINX_MEMORY_MB="${NGINX_MEMORY_MB:-512}"
NGINX_CORES="${NGINX_CORES:-1}"
NGINX_IP="${NGINX_WAN_IP:-10.10.10.70/24}"
NGINX_GW="${NGINX_WAN_GW:-10.10.10.1}"
NGINX_IP_ONLY="${NGINX_IP%%/*}"
LXC_TEMPLATE="${LXC_TEMPLATE:-local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst}"
SSH_PUBLIC_KEY="${SSH_PUBLIC_KEY:-$HOME/.ssh/id_rsa.pub}"

LLM_IP="${LLM_IP:-10.10.10.50}"
MONITORING_IP="${MONITORING_IP:-10.10.10.60}"
PROXMOX_PUB_IP="${PROXMOX_HOST:-}"

[[ -n "$PROXMOX_PUB_IP" ]] || die "PROXMOX_HOST not set in infra.yaml"
[[ -f "$SSH_PUBLIC_KEY" ]] || die "SSH public key not found: $SSH_PUBLIC_KEY"

mark_step "Deploying nginx proxy LXC ${NGINX_CTID}"

download_lxc_template() {
  local tmpl_name
  tmpl_name="$(basename "$LXC_TEMPLATE" | sed 's/^local:vztmpl\///')"
  local tmpl_path="/var/lib/vz/template/cache/${tmpl_name}"

  if [[ -f "$tmpl_path" ]]; then
    info "LXC template already exists: ${tmpl_path}"
    return 0
  fi

  info "Downloading LXC template..."
  pveam update
  pveam download local "${tmpl_name}" || \
    die "Failed to download template ${tmpl_name}. Run: pveam available --section system"
}

create_container() {
  if pct status "$NGINX_CTID" >/dev/null 2>&1; then
    if [[ "${FORCE_REBUILD:-0}" == "1" ]]; then
      warn "FORCE_REBUILD=1: destroying existing container ${NGINX_CTID}"
      pct stop "$NGINX_CTID" 2>/dev/null || true
      sleep 3
      pct destroy "$NGINX_CTID" --purge
    else
      info "Container ${NGINX_CTID} already exists, skipping creation"
      return 0
    fi
  fi

  info "Creating LXC container ${NGINX_CTID} on ${INTERNAL_BRIDGE} with IP ${NGINX_IP}"

  pct create "$NGINX_CTID" "$LXC_TEMPLATE" \
    --hostname "$NGINX_HOSTNAME" \
    --storage "$NGINX_STORAGE" \
    --rootfs "${NGINX_STORAGE}:${NGINX_DISK_GB}" \
    --memory "$NGINX_MEMORY_MB" \
    --cores "$NGINX_CORES" \
    --ostype ubuntu \
    --unprivileged 1 \
    --features nesting=1 \
    --net0 "name=eth0,bridge=${INTERNAL_BRIDGE},ip=${NGINX_IP},gw=${NGINX_GW}" \
    --nameserver "${DNS_SERVER:-1.1.1.1}" \
    --ssh-public-keys "$SSH_PUBLIC_KEY" \
    --start 1 \
    --onboot 1

  info "Container ${NGINX_CTID} created"
}

fix_stop_error() {
  pct stop "$NGINX_CTID" 2>/dev/null || true
}

wait_for_container() {
  info "Waiting for container to be ready"
  local waited=0
  while ! pct exec "$NGINX_CTID" -- true 2>/dev/null; do
    sleep 3
    waited=$((waited + 3))
    if (( waited > 60 )); then
      die "Container ${NGINX_CTID} not responding after 60s"
    fi
  done
  info "Container is ready"
}

install_nginx() {
  info "Installing nginx in container ${NGINX_CTID}"
  pct exec "$NGINX_CTID" -- bash -c "
    set -Eeuo pipefail
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y nginx curl
    systemctl enable nginx
    echo 'nginx installed'
  "
}

configure_nginx() {
  info "Configuring nginx reverse proxy"

  local nginx_conf
  nginx_conf="$(cat <<'EOF'
# llm-lab nginx reverse proxy
# Generated by proxy-deploy-nginx-proxy.sh

# Open WebUI
server {
    listen 8080;
    server_name _;
    location / {
        proxy_pass         http://${LLM_IP}:3000;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}

# Grafana
server {
    listen 3000;
    server_name _;
    location / {
        proxy_pass         http://${MONITORING_IP}:3000;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade \$http_upgrade;
        proxy_set_header   Connection "upgrade";
    }
}

# Prometheus
server {
    listen 9090;
    server_name _;
    location / {
        proxy_pass         http://${MONITORING_IP}:9090;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}

# Alertmanager
server {
    listen 9093;
    server_name _;
    location / {
        proxy_pass         http://${MONITORING_IP}:9093;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}

# Ollama API
server {
    listen 11434;
    server_name _;
    location / {
        proxy_pass         http://${LLM_IP}:11434;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        client_max_body_size 0;
    }
}
EOF
)"

  pct exec "$NGINX_CTID" -- bash -c "
    cat > /etc/nginx/sites-available/llm-lab << 'NGINXEOF'
${nginx_conf}
NGINXEOF
    ln -sf /etc/nginx/sites-available/llm-lab /etc/nginx/sites-enabled/llm-lab
    rm -f /etc/nginx/sites-enabled/default
    nginx -t
    systemctl reload nginx
    echo 'nginx configured'
  "
}

verify_nginx() {
  info "Verifying nginx in container"
  pct exec "$NGINX_CTID" -- bash -c "
    systemctl is-active nginx
    echo 'Listening ports:'
    ss -tlnp | grep nginx || true
  " 2>/dev/null || true
}

print_access_info() {
  info "Nginx proxy deployed — LXC ${NGINX_CTID}, internal IP: ${NGINX_IP_ONLY}"
  info "Run infra-setup-nft-rules.sh to configure DNAT and firewall"
  info "After that access via ${PROXMOX_PUB_IP}:"
  info "  Open WebUI:    http://${PROXMOX_PUB_IP}:8080"
  info "  Grafana:       http://${PROXMOX_PUB_IP}:3000"
  info "  Prometheus:    http://${PROXMOX_PUB_IP}:9090"
  info "  Alertmanager:  http://${PROXMOX_PUB_IP}:9093"
  info "  Ollama API:    http://${PROXMOX_PUB_IP}:11434"
}

download_lxc_template
create_container
wait_for_container
fix_locale
install_nginx
configure_nginx
verify_nginx
print_access_info

audit_log "Nginx proxy LXC ${NGINX_CTID} deployed"
